resources/nl/cemu.po
Just mention me if you need me to translate other strings for the dutch translation if there's an update with more strings. 👍
=> Add dutch translation

resources/pl/cemu.po
Add polish translation of Cemu.
=> Add polish translation

resources/it/cemu.po
There was some mistakes here and there, I have fixed some terms that are not correct in Italian.
=> Update the italian version of cemu.po

resources/it/cemu.po
Updated italian translation using the new .pot for Cemu 1.13.0. I also applied minor tweaks to existing translations.
=> Updated italian translation for Cemu 1.13.0

resources/pt/cemu.po
- Newly added strings are now translated
- Some of the existing translations were improved
=> Update pt translation (5a93d76)

resources/ja/cemu.po
Japanese translation check on 1.13.0f
=> Add Japanese Translation

resources/pl/cemu.po
Translated the recently added strings to polish.
=> Polish translation update

resources/pt/cemu.po
Translation based on f2c85d8 update
- New strings translated
- Improvements on some existing translations
=> Update pt translation (f2c85d8)

resources/zh/cemu.po
100% sure these two lines are "Google translations". They need to be fixed. 
Add: Optimize some texts to make them more accurate and natural.
=> Update zh cemu.po

resources/hu/cemu.po
Sorry about that; this one should be fine.
=> Small fixes

resources/zh/cemu.po
See commits log for info. I tweaked as little text as possible.
Comments are very welcome.
=> Minor fixes to Chinese translation

resources/pt/cemu.po
(should have addressed that a long time ago 😛)
=> Fix Portoguese translation

resources/hu/cemu.po
Hopefully I'm doing this correctly this time around.
=> Update Hungarian translation to 1.15.6

resources/nl/cemu.po
Updates the now pretty old translation to Cemu 1.19.0
=> Update Dutch translation to Cemu 1.19.0

resources/hu/cemu.po
I have one request, though: can I have some context for ‘Title checksum of {:08x}-{:08x}?’ I'm not sure of what the variables stand for.
=> Update Hungarian translation for 1.21.0

resources/zh/cemu.po
Update to the latest version.
Fixing the previous problem with the & symbol.
Several entries that should remain in English have been fixed.
=> Update Chinese translation for 1.21.4

resources/zh/cemu.po
=> Update Chinese translation for 1.22.1

resources/hu/cemu.po
There's one new string I'm not 100% sure about. Can I have some context for ‘Waiting for’?
Also, I've gone through the already translated strings to fix some things grammatically, and add some missing terminology.
=> Update Hungarian translation for 1.22.1

resources/en/cemu.pot
The English POT file has been replaced with the one generated by [this Cemu's repository CI workflow](https://github.com/cemu-project/Cemu/actions/runs/3118056562).
=> Update English POT to version 2.0-4

resources/ru/cemu.po
Fixed several annoying typos and incorrect wording of a couple of phrases.
=> Update Russian translation

resources/fr/cemu.po
=> Updated french language for Cemu 2.0-4

resources/de/cemu.po
This is an incomplete translation to the german language.
While this is still work-in-progress, it is probably better than having almost everything in english, which is how it currently is. 
I don't know when i will work more on this yet, so feel free to merge this PR as it is.
I will change this PR to a draft, if i start working on it again.
I could not test it, because i was unable to compile Cemu on Debian GNU/Linux 12, and the version for Ubuntu cannot use the translations on my computer (it shows english only).
=> Update the german translation

resources/ko/cemu.po
=> Update Korean translation! for 2.0-47

resources/de/cemu.po
The translation is almost complete now.
Currently based on the ".pot"-file from [there](https://github.com/cemu-project/Cemu/actions/runs/6360194170).
=> Update the German translation again

resources/ko/cemu.po
Fs00's POT update has been applied.
https://github.com/cemu-project/Cemu-Language/pull/109
=> Update Korean translation for 2.0-49

resources/en/cemu.pot
The POT file has been replaced with the one generated by [this CI run](https://github.com/cemu-project/Cemu/actions/runs/6189686328).
=> Update English POT to latest changes

resources/it/cemu.po
I've finally managed to complete the update of the Italian translation.
This time I have not only translated all missing strings (which were quite a lot since the last time I touched it a few years ago), but also went over my previous work and improved the wording and terminology here and there.
=> Update and refresh Italian translation

resources/fr/cemu.po
Update French localization for Cemu 2.0-55
=> Updated French translation for Cemu 2.0-55

resources/de/cemu.po
A small update and fixup, since cemu-project/Cemu#984 was merged after my translation-update-PR.
=> Update the German translation yet again

resources/fr/cemu.po
Updated French localization for Cemu 2.0-66
=> Update French translation for Cemu 2.0-66

resources/fr/cemu.po
Updated French translation to Cemu 2.1
=> Updated French localization to Cemu 2.1

resources/ar/‏‏cemu.po
We added Arabic translation to Cemu-Language
=> Added ‏‏Arabic translation 
